import type { Restaurant, MenuItem } from "./types"

export const restaurants: Restaurant[] = [
  {
    id: "rest-1",
    name: "Spice Garden",
    image: "/indian-vegetarian-restaurant-interior.jpg",
    cuisine: ["Indian", "South Indian"],
    rating: 4.5,
    deliveryTime: "25-35 min",
    deliveryFee: 2.99,
    minOrder: 15,
    isOpen: true,
    address: "123 Curry Lane, Food District",
    description: "Authentic Indian vegetarian cuisine with traditional recipes passed down through generations.",
  },
  {
    id: "rest-2",
    name: "Pasta Paradise",
    image: "/italian-vegetarian-restaurant-cozy.jpg",
    cuisine: ["Italian", "Mediterranean"],
    rating: 4.7,
    deliveryTime: "30-40 min",
    deliveryFee: 3.49,
    minOrder: 20,
    isOpen: true,
    address: "456 Roma Street, Downtown",
    description: "Fresh handmade pasta and authentic Italian vegetarian dishes.",
  },
  {
    id: "rest-3",
    name: "Green Dragon",
    image: "/asian-vegetarian-restaurant-modern.jpg",
    cuisine: ["Chinese", "Thai", "Asian"],
    rating: 4.3,
    deliveryTime: "20-30 min",
    deliveryFee: 2.49,
    minOrder: 12,
    isOpen: true,
    address: "789 Bamboo Ave, East Side",
    description: "Pan-Asian vegetarian delights with bold flavors and fresh ingredients.",
  },
  {
    id: "rest-4",
    name: "Taco Verde",
    image: "/mexican-vegetarian-restaurant-colorful.jpg",
    cuisine: ["Mexican", "Latin American"],
    rating: 4.6,
    deliveryTime: "25-35 min",
    deliveryFee: 2.99,
    minOrder: 15,
    isOpen: true,
    address: "321 Fiesta Blvd, West End",
    description: "Vibrant Mexican vegetarian street food with authentic flavors.",
  },
  {
    id: "rest-5",
    name: "Buddha Bowl",
    image: "/healthy-bowl-restaurant-minimalist.jpg",
    cuisine: ["Healthy", "Salads", "Bowls"],
    rating: 4.8,
    deliveryTime: "15-25 min",
    deliveryFee: 1.99,
    minOrder: 10,
    isOpen: true,
    address: "555 Wellness Way, Health Hub",
    description: "Nutritious and delicious grain bowls, fresh salads, and smoothies.",
  },
  {
    id: "rest-6",
    name: "Falafel House",
    image: "/middle-eastern-restaurant-warm-lighting.jpg",
    cuisine: ["Middle Eastern", "Mediterranean"],
    rating: 4.4,
    deliveryTime: "20-30 min",
    deliveryFee: 2.49,
    minOrder: 12,
    isOpen: false,
    address: "888 Hummus Lane, Central",
    description: "Traditional Middle Eastern vegetarian fare with homemade falafel and fresh pita.",
  },
]

export const menuItems: MenuItem[] = [
  // Spice Garden - Indian
  {
    id: "item-1",
    restaurantId: "rest-1",
    name: "Paneer Tikka Masala",
    description: "Grilled cottage cheese in rich tomato-based curry with aromatic spices",
    price: 14.99,
    image: "/paneer-tikka-masala-indian-curry.jpg",
    category: "Main Course",
    cuisine: "Indian",
    isVeg: true,
    isPopular: true,
  },
  {
    id: "item-2",
    restaurantId: "rest-1",
    name: "Vegetable Biryani",
    description: "Fragrant basmati rice layered with mixed vegetables and saffron",
    price: 12.99,
    image: "/vegetable-biryani.png",
    category: "Rice",
    cuisine: "Indian",
    isVeg: true,
    isPopular: true,
  },
  {
    id: "item-3",
    restaurantId: "rest-1",
    name: "Masala Dosa",
    description: "Crispy rice crepe filled with spiced potato filling, served with chutneys",
    price: 10.99,
    image: "/masala-dosa-south-indian.png",
    category: "South Indian",
    cuisine: "South Indian",
    isVeg: true,
  },
  {
    id: "item-4",
    restaurantId: "rest-1",
    name: "Dal Makhani",
    description: "Creamy black lentils slow-cooked with butter and spices",
    price: 11.99,
    image: "/dal-makhani-lentil-curry.jpg",
    category: "Main Course",
    cuisine: "Indian",
    isVeg: true,
  },
  {
    id: "item-5",
    restaurantId: "rest-1",
    name: "Samosa (2 pcs)",
    description: "Crispy pastry filled with spiced potatoes and peas",
    price: 5.99,
    image: "/vegetable-samosa-indian-snack.jpg",
    category: "Starters",
    cuisine: "Indian",
    isVeg: true,
    isSpicy: true,
  },

  // Pasta Paradise - Italian
  {
    id: "item-6",
    restaurantId: "rest-2",
    name: "Margherita Pizza",
    description: "Classic pizza with fresh mozzarella, tomatoes, and basil",
    price: 15.99,
    image: "/margherita-pizza-fresh-basil.jpg",
    category: "Pizza",
    cuisine: "Italian",
    isVeg: true,
    isPopular: true,
  },
  {
    id: "item-7",
    restaurantId: "rest-2",
    name: "Penne Arrabbiata",
    description: "Penne pasta in spicy tomato sauce with garlic and chili",
    price: 13.99,
    image: "/penne-arrabbiata-pasta.jpg",
    category: "Pasta",
    cuisine: "Italian",
    isVeg: true,
    isSpicy: true,
  },
  {
    id: "item-8",
    restaurantId: "rest-2",
    name: "Mushroom Risotto",
    description: "Creamy arborio rice with wild mushrooms and parmesan",
    price: 16.99,
    image: "/creamy-mushroom-risotto.png",
    category: "Rice",
    cuisine: "Italian",
    isVeg: true,
    isPopular: true,
  },
  {
    id: "item-9",
    restaurantId: "rest-2",
    name: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, garlic, and basil",
    price: 7.99,
    image: "/bruschetta-tomato-basil.jpg",
    category: "Starters",
    cuisine: "Italian",
    isVeg: true,
  },

  // Green Dragon - Asian
  {
    id: "item-10",
    restaurantId: "rest-3",
    name: "Vegetable Pad Thai",
    description: "Stir-fried rice noodles with tofu, vegetables, and tamarind sauce",
    price: 12.99,
    image: "/vegetable-pad-thai-noodles.jpg",
    category: "Noodles",
    cuisine: "Thai",
    isVeg: true,
    isPopular: true,
  },
  {
    id: "item-11",
    restaurantId: "rest-3",
    name: "Kung Pao Tofu",
    description: "Crispy tofu with peanuts, chilies, and Sichuan peppers",
    price: 13.99,
    image: "/kung-pao-tofu-spicy.jpg",
    category: "Main Course",
    cuisine: "Chinese",
    isVeg: true,
    isSpicy: true,
  },
  {
    id: "item-12",
    restaurantId: "rest-3",
    name: "Vegetable Spring Rolls",
    description: "Crispy rolls filled with cabbage, carrots, and glass noodles",
    price: 6.99,
    image: "/vegetable-spring-rolls-crispy.jpg",
    category: "Starters",
    cuisine: "Chinese",
    isVeg: true,
  },
  {
    id: "item-13",
    restaurantId: "rest-3",
    name: "Green Curry",
    description: "Thai green curry with mixed vegetables and coconut milk",
    price: 14.99,
    image: "/thai-green-curry-vegetables.jpg",
    category: "Main Course",
    cuisine: "Thai",
    isVeg: true,
    isSpicy: true,
  },

  // Taco Verde - Mexican
  {
    id: "item-14",
    restaurantId: "rest-4",
    name: "Bean & Cheese Burrito",
    description: "Flour tortilla stuffed with black beans, cheese, rice, and salsa",
    price: 10.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Burritos",
    cuisine: "Mexican",
    isVeg: true,
    isPopular: true,
  },
  {
    id: "item-15",
    restaurantId: "rest-4",
    name: "Veggie Quesadilla",
    description: "Grilled tortilla with melted cheese, peppers, and onions",
    price: 9.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Quesadillas",
    cuisine: "Mexican",
    isVeg: true,
  },
  {
    id: "item-16",
    restaurantId: "rest-4",
    name: "Loaded Nachos",
    description: "Tortilla chips with beans, cheese, jalapeños, guacamole, and sour cream",
    price: 11.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Starters",
    cuisine: "Mexican",
    isVeg: true,
    isSpicy: true,
  },
  {
    id: "item-17",
    restaurantId: "rest-4",
    name: "Tacos (3 pcs)",
    description: "Soft corn tortillas with grilled vegetables, beans, and fresh salsa",
    price: 8.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Tacos",
    cuisine: "Mexican",
    isVeg: true,
  },

  // Buddha Bowl - Healthy
  {
    id: "item-18",
    restaurantId: "rest-5",
    name: "Mediterranean Bowl",
    description: "Quinoa, falafel, hummus, cucumber, tomatoes, and tahini dressing",
    price: 13.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Bowls",
    cuisine: "Mediterranean",
    isVeg: true,
    isPopular: true,
  },
  {
    id: "item-19",
    restaurantId: "rest-5",
    name: "Asian Crunch Salad",
    description: "Mixed greens, edamame, crispy noodles, and sesame ginger dressing",
    price: 11.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Salads",
    cuisine: "Asian",
    isVeg: true,
  },
  {
    id: "item-20",
    restaurantId: "rest-5",
    name: "Acai Smoothie Bowl",
    description: "Blended acai with banana, topped with granola and fresh berries",
    price: 10.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Smoothie Bowls",
    cuisine: "Healthy",
    isVeg: true,
    isPopular: true,
  },

  // Falafel House - Middle Eastern
  {
    id: "item-21",
    restaurantId: "rest-6",
    name: "Falafel Wrap",
    description: "Crispy falafel in warm pita with hummus, vegetables, and tahini",
    price: 10.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Wraps",
    cuisine: "Middle Eastern",
    isVeg: true,
    isPopular: true,
  },
  {
    id: "item-22",
    restaurantId: "rest-6",
    name: "Hummus Platter",
    description: "Creamy hummus served with warm pita bread and olives",
    price: 8.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Starters",
    cuisine: "Middle Eastern",
    isVeg: true,
  },
  {
    id: "item-23",
    restaurantId: "rest-6",
    name: "Shakshuka",
    description: "Poached eggs in spiced tomato sauce with crusty bread",
    price: 12.99,
    image: "/placeholder.svg?height=200&width=200",
    category: "Main Course",
    cuisine: "Middle Eastern",
    isVeg: true,
    isSpicy: true,
  },
]

export const cuisineTypes = [
  "All",
  "Indian",
  "Italian",
  "Chinese",
  "Thai",
  "Mexican",
  "Mediterranean",
  "Middle Eastern",
  "Healthy",
]
